import Fastify from 'fastify';
import cookie from '@fastify/cookie'; import cors from '@fastify/cors'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit'; import statik from '@fastify/static';
import { createHmac, randomBytes, timingSafeEqual } from 'node:crypto'; import { join } from 'node:path'; import { z } from 'zod';
import { prisma, getMercadoPagoConfig, getTelegramConfig, maskSecret } from './config.js';
import { createOrder } from './services/orders.js'; import { createCheckout, getPayment } from './integrations/mercadopago.js'; import { sendSaleNotification } from './integrations/telegram.js';

const isProduction = process.env.NODE_ENV === 'production';
if (isProduction && !process.env.SESSION_SECRET) throw new Error('SESSION_SECRET é obrigatório em produção');
const appUrl = (process.env.APP_URL || 'http://localhost:3000').replace(/\/$/, '');
const app = Fastify({ logger: { level: process.env.LOG_LEVEL || 'info', redact: ['req.headers.authorization', 'req.headers.cookie', '*.accessToken', '*.token', '*.password'] } });
await app.register(cookie, { secret: process.env.SESSION_SECRET || 'development-only-change-me' });
await app.register(cors, { origin: isProduction ? appUrl : [appUrl, 'http://localhost:5173'], credentials: true });
await app.register(helmet); await app.register(rateLimit, { max: 100, timeWindow: '1 minute' });
const sessionMaxAge = 60 * 60 * 8;
function sessionValue(email: string) { return `${email}|${Date.now() + sessionMaxAge * 1000}|${randomBytes(16).toString('hex')}`; }
function isValidSession(request: any) { const parsed = request.unsignCookie(request.cookies.admin_session || ''); if (!parsed.valid) return false; const [email, expires] = parsed.value.split('|'); return email === process.env.ADMIN_EMAIL && Number(expires) > Date.now(); }
const admin = async (request: any, reply: any) => { if (!isValidSession(request)) return reply.code(401).send({ error: 'Não autenticado' }); };
const csrf = async (request: any, reply: any) => { if (!['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method)) return; const origin = request.headers.origin; if (origin && origin !== appUrl && !( !isProduction && origin === 'http://localhost:5173')) return reply.code(403).send({ error: 'Origem não permitida' }); };
const productSchema = z.object({ name: z.string().trim().min(2).max(160), description: z.string().trim().max(1000), category: z.string().trim().min(2).max(100), quantity: z.number().int().positive(), salePrice: z.number().int().positive(), supplierCost: z.number().int().nonnegative(), active: z.boolean().default(true), sortOrder: z.number().int().default(0) });

app.get('/api/products', async () => prisma.product.findMany({ where: { active: true }, select: { id: true, name: true, description: true, category: true, quantity: true, salePrice: true, sortOrder: true }, orderBy: { sortOrder: 'asc' } }));
app.get('/api/products/:id', async (request: any, reply) => { const product = await prisma.product.findFirst({ where: { id: request.params.id, active: true }, select: { id: true, name: true, description: true, category: true, quantity: true, salePrice: true } }); return product || reply.code(404).send({ error: 'Produto não encontrado' }); });
app.post('/api/orders', { preHandler: csrf }, async (request: any, reply) => { const input = z.object({ productId: z.string().min(1).max(64), instagramUsername: z.string().trim().regex(/^@?[A-Za-z0-9._]{1,30}$/), customerName: z.string().trim().max(100).optional(), customerEmail: z.string().trim().email().max(254), acceptedTerms: z.literal(true) }).safeParse(request.body); if (!input.success) return reply.code(400).send({ error: 'Dados inválidos' }); try { const order = await createOrder(input.data); const checkout = await createCheckout(order); await prisma.order.update({ where: { id: order.id }, data: { mercadoPagoReference: checkout.reference } }); return { publicId: order.publicId, checkoutUrl: checkout.url }; } catch (error) { request.log.warn({ err: error }, 'Order checkout creation failed'); return reply.code(400).send({ error: 'Não foi possível iniciar o pagamento' }); } });
app.get('/api/orders/:publicId', async (request: any, reply) => { const order = await prisma.order.findUnique({ where: { publicId: request.params.publicId }, select: { publicId: true, productNameSnapshot: true, amount: true, paymentStatus: true, fulfillmentStatus: true } }); return order || reply.code(404).send({ error: 'Pedido não encontrado' }); });

app.post('/api/admin/login', { preHandler: csrf }, async (request: any, reply) => { const input = z.object({ email: z.string().trim().email().max(254), password: z.string().min(1).max(128) }).safeParse(request.body); const expected = process.env.ADMIN_PASSWORD || ''; const valid = !!input.success && !!process.env.ADMIN_EMAIL && !!expected && input.data.email === process.env.ADMIN_EMAIL && timingSafeEqual(Buffer.from(input.data.password.padEnd(128)), Buffer.from(expected.slice(0, 128).padEnd(128))); if (!valid) return reply.code(401).send({ error: 'Credenciais inválidas' }); reply.setCookie('admin_session', sessionValue(process.env.ADMIN_EMAIL!), { signed: true, httpOnly: true, sameSite: 'strict', secure: isProduction, path: '/', maxAge: sessionMaxAge }); return { ok: true }; });
app.post('/api/admin/logout', { preHandler: [admin, csrf] }, async (_request, reply) => { reply.clearCookie('admin_session', { path: '/' }); return { ok: true }; });
app.get('/api/admin/session', async (request: any) => ({ authenticated: isValidSession(request) }));
app.get('/api/admin/products', { preHandler: admin }, async () => prisma.product.findMany({ orderBy: { sortOrder: 'asc' }));
app.post('/api/admin/products', { preHandler: [admin, csrf] }, async (request: any, reply) => { const input = productSchema.safeParse(request.body); return input.success ? prisma.product.create({ data: input.data }) : reply.code(400).send({ error: 'Dados inválidos' }); });
app.patch('/api/admin/products/:id', { preHandler: [admin, csrf] }, async (request: any, reply) => { const input = productSchema.partial().safeParse(request.body); if (!input.success) return reply.code(400).send({ error: 'Dados inválidos' }); try { return await prisma.product.update({ where: { id: request.params.id }, data: input.data }); } catch { return reply.code(404).send({ error: 'Produto não encontrado' }); } });
app.delete('/api/admin/products/:id', { preHandler: [admin, csrf] }, async (request: any, reply) => { try { return await prisma.product.update({ where: { id: request.params.id }, data: { active: false } }); } catch { return reply.code(404).send({ error: 'Produto não encontrado' }); } });
app.get('/api/admin/orders', { preHandler: admin }, async (request: any) => { const filters = z.object({ paymentStatus: z.enum(['pending','approved','rejected','cancelled','refunded']).optional(), fulfillmentStatus: z.enum(['waiting_payment','paid','supplier_ordered','completed','cancelled']).optional() }).safeParse(request.query); return prisma.order.findMany({ where: filters.success ? filters.data : {}, orderBy: { createdAt: 'desc' } }); });
app.patch('/api/admin/orders/:id', { preHandler: [admin, csrf] }, async (request: any, reply) => { const input = z.object({ fulfillmentStatus: z.enum(['paid', 'supplier_ordered', 'completed', 'cancelled']) }).safeParse(request.body); if (!input.success) return reply.code(400).send({ error: 'Status inválido' }); try { return await prisma.order.update({ where: { id: request.params.id }, data: input.data }); } catch { return reply.code(404).send({ error: 'Pedido não encontrado' }); } });
app.get('/api/admin/dashboard', { preHandler: admin }, async () => { const orders = await prisma.order.findMany(); const approved = orders.filter(o => o.paymentStatus === 'approved'); return { sales: approved.length, revenue: approved.reduce((n,o) => n + o.amount, 0), costs: approved.reduce((n,o) => n + o.supplierCostSnapshot, 0), profit: approved.reduce((n,o) => n + o.grossProfitSnapshot, 0), pending: orders.filter(o => o.fulfillmentStatus === 'waiting_payment').length, paid: orders.filter(o => o.fulfillmentStatus === 'paid').length, supplierOrdered: orders.filter(o => o.fulfillmentStatus === 'supplier_ordered').length, completed: orders.filter(o => o.fulfillmentStatus === 'completed').length }; });
app.get('/api/admin/settings', { preHandler: admin }, async () => { const mp = await getMercadoPagoConfig(), tg = await getTelegramConfig(); return { mercadoPago: { environment: mp.environment, accessToken: maskSecret(mp.accessToken), publicKey: maskSecret(mp.publicKey), configured: !!mp.accessToken && !!mp.publicKey }, telegram: { botToken: maskSecret(tg.token), chatId: tg.chatId, configured: !!tg.token && !!tg.chatId } }; });
app.put('/api/admin/settings', { preHandler: [admin, csrf] }, async (request: any, reply) => { const input = z.object({ mpEnvironment: z.enum(['test','production']).optional(), mpAccessToken: z.string().trim().min(1).optional(), mpPublicKey: z.string().trim().min(1).optional(), telegramBotToken: z.string().trim().min(1).optional(), telegramChatId: z.string().trim().min(1).optional() }).safeParse(request.body); if (!input.success) return reply.code(400).send({ error: 'Dados inválidos' }); const values: Record<string, string | undefined> = { mp_environment: input.data.mpEnvironment, mp_access_token: input.data.mpAccessToken, mp_public_key: input.data.mpPublicKey, telegram_bot_token: input.data.telegramBotToken, telegram_chat_id: input.data.telegramChatId }; await Promise.all(Object.entries(values).filter(([, value]) => value).map(([key, value]) => prisma.appSetting.upsert({ where: { key }, create: { key, value: value! }, update: { value: value! } }))); return { ok: true }; });
app.post('/api/admin/test/mercadopago', { preHandler: [admin, csrf] }, async () => { const { accessToken } = await getMercadoPagoConfig(); if (!accessToken) return { ok: false, status: 'Não configurado' }; const response = await fetch('https://api.mercadopago.com/users/me', { headers: { Authorization: `Bearer ${accessToken}` }, signal: AbortSignal.timeout(10_000) }); return { ok: response.ok, status: response.ok ? 'Conectado' : 'Não foi possível validar as credenciais' }; });
app.post('/api/admin/test/telegram', { preHandler: [admin, csrf] }, async () => { const config = await getTelegramConfig(); if (!config.token || !config.chatId) return { ok: false, status: 'Não configurado' }; const response = await fetch(`https://api.telegram.org/bot${config.token}/getMe`, { signal: AbortSignal.timeout(10_000) }); return { ok: response.ok, status: response.ok ? 'Conectado' : 'Não foi possível validar as credenciais' }; });
function validSignature(request: any, paymentId: string, secret: string) { if (!secret) return true; const signature = String(request.headers['x-signature'] || ''); const requestId = String(request.headers['x-request-id'] || ''); const timestamp = /(?:^|,)\s*ts=([^,]+)/.exec(signature)?.[1]; const received = /(?:^|,)\s*v1=([a-f0-9]+)/i.exec(signature)?.[1]; if (!timestamp || !received) return false; const manifest = `id:${paymentId};request-id:${requestId};ts:${timestamp};`; const expected = createHmac('sha256', secret).update(manifest).digest('hex'); return received.length === expected.length && timingSafeEqual(Buffer.from(received), Buffer.from(expected)); }
const paymentStatus = (status: string) => ({ approved: 'approved', rejected: 'rejected', cancelled: 'cancelled', refunded: 'refunded' }[status] || 'pending') as 'approved' | 'rejected' | 'cancelled' | 'refunded' | 'pending';
app.post('/api/webhooks/mercadopago', async (request: any, reply) => { const body = request.body || {}; const paymentId = String(body.data?.id || request.query?.['data.id'] || ''); if (!paymentId) return reply.code(200).send({ received: true }); const config = await getMercadoPagoConfig(); if (!validSignature(request, paymentId, config.webhookSecret)) return reply.code(401).send({ error: 'Assinatura inválida' }); const deliveryId = String(request.headers['x-request-id'] || `${body.type || body.topic || 'payment'}:${paymentId}`); try { const payment: any = await getPayment(paymentId); const orderId = String(payment.external_reference || ''); const order = orderId ? await prisma.order.findUnique({ where: { id: orderId } }) : null; try { await prisma.paymentEvent.create({ data: { externalId: deliveryId, topic: String(body.type || body.topic || 'payment'), payload: JSON.stringify(body), orderId: order?.id } }); } catch (error: any) { if (error?.code === 'P2002') return { received: true }; throw error; }
  if (!order) return { received: true }; const status = paymentStatus(String(payment.status)); const firstApproval = status === 'approved' && order.paymentStatus !== 'approved'; const updated = await prisma.order.update({ where: { id: order.id }, data: { paymentStatus: status, mercadoPagoPaymentId: paymentId, fulfillmentStatus: status === 'approved' ? 'paid' : status === 'cancelled' ? 'cancelled' : order.fulfillmentStatus } });
  if (firstApproval) { const claimed = await prisma.order.updateMany({ where: { id: updated.id, telegramNotifiedAt: null, telegramNotificationProcessingAt: null }, data: { telegramNotificationProcessingAt: new Date(), telegramNotificationError: null } }); if (claimed.count) { try { await sendSaleNotification(updated); await prisma.order.update({ where: { id: updated.id }, data: { telegramNotifiedAt: new Date(), telegramNotificationProcessingAt: null, telegramNotificationError: null } }); } catch (error) { request.log.error({ err: error, orderId: updated.id }, 'Telegram notification failed'); await prisma.order.update({ where: { id: updated.id }, data: { telegramNotificationProcessingAt: null, telegramNotificationError: 'Falha no envio; reprocessar notificação manualmente.' } }); } } }
  return { received: true };
 } catch (error) { request.log.error({ err: error, paymentId }, 'Webhook processing failed'); return reply.code(500).send({ error: 'Falha temporária no processamento' }); } });
await app.register(statik, { root: join(process.cwd(), 'dist/web'), prefix: '/' });
app.setNotFoundHandler((request, reply) => request.url.startsWith('/api/') ? reply.code(404).send({ error: 'Não encontrado' }) : reply.sendFile('index.html'));
app.setErrorHandler((error, request, reply) => { request.log.error(error); if (!reply.sent) reply.code((error as any).statusCode || 500).send({ error: 'Erro interno' }); });
await app.listen({ port: Number(process.env.PORT || 3000), host: '0.0.0.0' });
